vim.pack.add({
    { src = "https://github.com/nvim-lua/plenary.nvim" },
    { src = "https://github.com/nvim-telescope/telescope.nvim" },
    { src = "https://github.com/nvim-tree/nvim-web-devicons" },
    { src = 'https://github.com/neovim/nvim-lspconfig' },
    { src = 'https://github.com/rose-pine/neovim' },
    { src = 'https://github.com/rebelot/kanagawa.nvim' },
    { src = 'https://github.com/shaunsingh/nord.nvim' },
    { src = 'https://github.com/tpope/vim-fugitive' },
    { src = "https://github.com/mbbill/undotree" },
    { src = "https://github.com/nvim-treesitter/nvim-treesitter" },
    { src = "https://github.com/mason-org/mason.nvim" },
    { src = "https://github.com/j-hui/fidget.nvim" },
    { src = "https://github.com/l3mon4d3/luasnip" },
    { src = "https://github.com/hrsh7th/nvim-cmp" },
    { src = "https://github.com/saadparwaiz1/cmp_luasnip" },
    { src = "https://github.com/hrsh7th/cmp-nvim-lsp" },
    { src = "https://github.com/hrsh7th/cmp-buffer" },
    { src = "https://github.com/hrsh7th/cmp-path" },
    { src = "https://github.com/hrsh7th/cmp-cmdline" },
    {
        src = "https://github.com/ThePrimeagen/harpoon",
        version = 'harpoon2',
        name = 'harpoon',
    },
    { src = "https://github.com/sindrets/diffview.nvim" },
})
