local map = vim.keymap.set
map("n", "<leader>pv", "<cmd>Explore<CR>", { desc = "Netrw file explorer" })
map("n", "<leader>pf", ":find ", { desc = "Find file (Tab for fuzzy completion)" })
map("n", "<C-g>", ":find ", { desc = "Find file" })
map("n", "<leader>pg", "<cmd>Grep<CR>", { desc = "Search text into quickfix" })
map("n", "<leader>pws", function() require("server.tools").grep(vim.fn.expand("<cword>")) end,
    { desc = "Search word as literal text" })
map("n", "<leader>pWs", function() require("server.tools").grep(vim.fn.expand("<cWORD>")) end,
    { desc = "Search WORD as literal text" })
map("n", "<leader>vh", ":help ", { desc = "Help (Tab to complete)" })
map("n", "<leader>u", "<cmd>Undotree<CR>", { desc = "Built-in undo tree" })
map("n", "<leader>gs", "<cmd>Git status --short --branch<CR>", { desc = "Git status" })
map("n", "<leader>gd", "<cmd>Git diff<CR>", { desc = "Git diff" })
map("n", "<leader>gl", "<cmd>Git log -15 --oneline<CR>", { desc = "Git log" })
map("n", "<leader>gt", "<cmd>botright 12split | terminal<CR>", { desc = "Terminal" })
map("t", "<Esc><Esc>", "<C-\\><C-n>", { desc = "Leave terminal mode" })

map("v", "J", ":m '>+1<CR>gv=gv", { desc = "Move lines down" })
map("v", "K", ":m '<-2<CR>gv=gv", { desc = "Move lines up" })
map("n", "J", "mzJ`z")
map("n", "<C-d>", "<C-d>zz")
map("n", "<C-u>", "<C-u>zz")
map("n", "n", "nzzzv")
map("n", "N", "Nzzzv")
map("x", "<leader>p", '"_dP')
map({ "n", "v" }, "<leader>y", '"+y', { desc = "Yank using configured clipboard provider" })
map("n", "<leader>Y", '"+Y')
map("i", "<C-c>", "<Esc>")
map("n", "Q", "<nop>")
map("n", "<C-b>", "<C-a>")
map("n", "<leader>s", [[:%s/\<<C-r><C-w>\>/<C-r><C-w>/gI<Left><Left><Left>]])
map("n", "<leader>j", "<cmd>cnext<CR>zz", { desc = "Next quickfix result" })
map("n", "<leader>k", "<cmd>cprevious<CR>zz", { desc = "Previous quickfix result" })
map("n", "<leader>q", "<cmd>copen<CR>", { desc = "Quickfix list" })
map("n", "<leader>b", ":buffer ", { desc = "Switch buffer (Tab to complete)" })
map("n", "<leader>a", "mA", { desc = "Bookmark file using global mark A" })
map("n", "<C-e>", "<cmd>marks ABCDEFGHIJKLMNOPQRSTUVWXYZ<CR>", { desc = "List native file marks" })
map("n", "<leader>ee", function()
    vim.snippet.expand("if err != nil {\n\t${1:return err}\n}\n$0")
end, { desc = "Native Go error snippet" })
map("n", "<leader>f", "<cmd>Format<CR>", { desc = "Format explicitly" })
map("n", "<leader>vd", vim.diagnostic.open_float, { desc = "Diagnostic details" })
map("n", "<leader>vca", vim.lsp.buf.code_action, { desc = "Code action" })
map("n", "<leader>vrr", vim.lsp.buf.references, { desc = "References" })
map("n", "<leader>vrn", vim.lsp.buf.rename, { desc = "Rename" })
map("n", "<leader>vws", vim.lsp.buf.workspace_symbol, { desc = "Workspace symbols" })
map("n", "<leader>th", function()
    vim.lsp.inlay_hint.enable(not vim.lsp.inlay_hint.is_enabled({ bufnr = 0 }), { bufnr = 0 })
end, { desc = "Toggle inlay hints" })
